version: '3.9'

services:

  # webapp:
    # container_name: server_webapp
    # image: node:16.15.1
    # working_dir: /home/webapp
    # command: /bin/sh -c "yarn install && yarn db:push && yarn prod"
    # restart: on-failure
    # volumes:
    #  - .:/home/webapp
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    # ports:
    #  - 3000:3000
    # environment:
    #  DATABASE_URL: "mysql://root:password@mysql:3306/webapp"
    #  NODE_ENV: local
    #  PORT: 3000

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
